---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      bundler_args:
      env: BEAKER_set=centos-6-x64
      rvm: default
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      bundler_args:
      env: BEAKER_set=centos-7-x64
      rvm: default
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      bundler_args:
      env: BEAKER_set=ubuntu-14.04-x64
      rvm: default
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      bundler_args:
      env: BEAKER_set=ubuntu-16.04-x64
      rvm: default
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      bundler_args:
      env: BEAKER_set=ubuntu-18.04-x64
      rvm: default
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      bundler_args:
      env: BEAKER_set=debian-9-x64
      rvm: default
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      env: CHECK="syntax lint metadata_lint check:syml
    -
      env: CHECK=parallel_spec
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
